#!/bin/bash
set -e

echo
echo "===> Build started at $(date)"
echo
START=$SECONDS

# Unconditionally print elapsed build time at exit
function finish {
  echo "===> Elapsed time: $(($SECONDS - $START)) seconds"
}
trap finish EXIT

echo "---> building CHART: ${CHART}"

echo "---> Preparing source..."
#HELMDIR="helm_dir"
#mkdir -p helm_dir

#cp -Rf /tmp/src/. $HELMDIR

#

HELMVERSION=$(helm version --client)


echo "** helmi **"
echo "============================================="
echo "|| HELMVERSION: $HELMVERSION"
echo "|| CHART: $CHART"
echo "|| OCP_VERSION: $OCP_VERSION"
echo "============================================="



echo "---> Building helm package..."

charts=$(find /tmp/src/* -maxdepth 1 -name Chart.yaml -exec dirname "{}" \;)
for chart in $charts; do
  echo "----> Packaging ${chart}"
  helm package \
    --destination="$HOME" \
    --save=true \
    "$chart"
    ERR=$?
  if [ $ERR -ne 0 ]; then
    echo "Aborting due to error code $ERR"
    exit $ERR
  fi
done

echo "---> Building finish"

#echo "install binary"
ls -larht $HOME

echo
echo "===> Build completed at $(date)"
